Repository theopcoder/PedestriaBotOfficial, pull requests merged in 2021-01, with the labels that each got.

#4 Fix Spacing Issues
  BotData.js
  Changelogs/2.0.0 Changelog
Labels: documentation

#6 2.1.3 Feature Update
  BotData.js
  Changelogs/2.0.0 Changelog
  README.md
  commands/admin/settings.js
  index.js
Labels: documentation, enhancement

#11 Update README.md
  README.md
Labels: documentation

#12 Fixed spelling mistake
  README.md
Labels: Merge
